import { useState } from 'react'
import './Landing.css'

export default function Landing({ onSandboxCreated, showToast }) {
  const [loading, setLoading] = useState(false)

  async function createSandbox() {
    setLoading(true)
    try {
      const res = await fetch('/api/sandbox/start', { method: 'POST' })
      if (!res.ok) throw new Error(`Server responded with ${res.status}`)
      const data = await res.json()
      onSandboxCreated(data)
    } catch (err) {
      showToast('❌ ' + err.message, 'error')
      setLoading(false)
    }
  }

  return (
    <div className="landing">
      {/* Decorative grid */}
      <div className="landing-grid" aria-hidden="true" />

      {/* Glow orbs */}
      <div className="orb orb-purple" aria-hidden="true" />
      <div className="orb orb-cyan"   aria-hidden="true" />

      <main className="landing-content">
        <div className="badge">
          <span className="badge-dot" />
          AI-Powered Sandbox IDE
        </div>

        <h1 className="landing-title">
          Build frontends<br />
          <span className="gradient-text">with AI, instantly</span>
        </h1>

        <p className="landing-sub">
          Spin up an isolated sandbox, describe what you want to build,
          and watch an AI engineer ship your React frontend in real time —
          with live preview.
        </p>

        <button
          id="create-sandbox-btn"
          className={`create-btn ${loading ? 'loading' : ''}`}
          onClick={createSandbox}
          disabled={loading}
        >
          {loading ? (
            <>
              <span className="spinner btn-spinner" />
              <span>Spinning up sandbox…</span>
            </>
          ) : (
            <>
              <span className="btn-icon">⚡</span>
              <span>Create Sandbox</span>
            </>
          )}
        </button>

        <div className="feature-chips">
          {['AI Code Generation', 'Live Preview', 'Instant Sandbox', 'React + Vite'].map(f => (
            <div className="chip" key={f}>
              <span className="chip-dot" />
              {f}
            </div>
          ))}
        </div>

        <div className="landing-stack-preview" aria-hidden="true">
          <div className="code-card">
            <div className="code-card-dots">
              <span /><span /><span />
            </div>
            <pre className="code-snippet">{`// AI-generated by FrontendForge
export default function Hero() {
  return (
    <section className="hero">
      <h1>Your idea, shipped.</h1>
      <button>Get started →</button>
    </section>
  )
}`}</pre>
          </div>
        </div>
      </main>
    </div>
  )
}
